### ISSUE TITLE
关于更新0.8.9、更换12490F的问题

### ISSUE THREAD

**Issue by HarveyXWu** [geekfory/Hackintosh-EFI-ASUS-H610M-A-12400-6600xt-AX201#4]
大佬你好：
有幸在远景看到你的分享，同主板，想请教几个问题
1. 想请问如果按照你的efi为基础，直接更新0.8.9，有哪些需要特别注意的点吗？
2. 我的u是12490F，efi需要改动什么地方吗？（例如cpu仿冒之类的）

十分感谢！

**Comment by geekfory** [comment]
大佬不敢当，我也是入门级选手。
1，升级建议用OCAuxiliaryTools，升完后有个验证按钮，可以查到有问题的地方。因不同版本之间开发者增加了功能，所以config会有些地方缺数据，根据提示找到对应位置填入数据即可。
2，efi修改：1 关于里CPU型号问题可以搜索config查找12400替换为12490F即可。2 目前配置睿频应该没问题。3 如果你没ax201网卡的话需要禁用相关驱动。

**Comment by HarveyXWu** [comment]
> 
十分感谢老哥的解答！
另外想问一下你的ax201是那种wifigo插在板子网卡口的吗？
目前用起来怎么样呢？我比较好奇airpods连接的稳定性，个人用airpods较多。
感谢！

**Comment by geekfory** [comment]
是的就是wifigo那种，主板预留了那个接口。
稳定还好，不经常用，偶尔连下蓝牙音箱听歌。
你用airpods的话个人是建议买博通的免驱网卡，和苹果手机之间交互性比较好些

**Comment by HarveyXWu** [comment]
> 是的就是wifigo那种，主板预留了那个接口。 稳定还好，不经常用，偶尔连下蓝牙音箱听歌。 你用airpods的话个人是建议买博通的免驱网卡，和苹果手机之间交互性比较好些

好的，感谢指导！
